### ISSUE TITLE
frida.ProcessNotFoundError: unable to find process with name 'mediadrmserver'

### ISSUE THREAD

**Issue by bencooper1** [Avalonswanderer/widevinel3_Android_PoC#3]
I tested on Android Emulator google-play API 30 (Android 11) x86 and got error  unable to find process with name 'mediadrmserver' (python script.py new):

```
Traceback (most recent call last):
  File "/Users/admin/Downloads/widevinel3_Android_PoC/script/script.py", line 100, in <module>
    main()
  File "/Users/admin/Downloads/widevinel3_Android_PoC/script/script.py", line 65, in main
    session = device.attach(mediadrm)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 1193, in _pid_of
    return self.get_process(target).pid
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 969, in get_process
    raise _frida.ProcessNotFoundError(f"unable to find process with name '{process_name}'")
frida.ProcessNotFoundError: unable to find process with name 'mediadrmserver'
```

Can you please check again and give some update? Thank!

**Comment by Avalonswanderer** [comment]
It migh be because of the process name being mediaserver starting from Android 7. Use the option new with the script to search for it
